global:
  message: Welcome to the dev Environment
server:
  port: 8082
message: Hello from Dev!
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
 #jdbc:mysql://localhost:3306/customer_master
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
